language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - NUMPY_VERSION=1.7.0
# command to install dependencies
install:
  - pip install -q numpy==$NUMPY_VERSION
  - python setup.py -q install
# command to run tests
script: python tests/minepy_test.py